version: '3.8'

services:
  sales-savvy-app:
    image: sales-savvy-app
    container_name: sales-savvy-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    env_file:
      - ./src/main/resources/.env